#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
dir=$PWD

############################################
# Install Node-RED
############################################
# Copy over our Quick Install App
cd $dir
rsync -r ./Installers/ /usr/local/hestia/web/src/app/WebApp/Installers/
/usr/local/hestia/bin/v-invoke-plugin nodered_install

# Notify installation has finished
/usr/local/hestia/bin/v-add-user-notification admin "Node-RED" "&#128571; Node-RED plugin has finished installing."