#!/bin/bash

############################################
# Uninstall Node-RED
############################################
rm -rf /opt/node-red/v3.0.2/node-red

# Remove Quick Install App
rm -rf /usr/local/hestia/web/src/app/WebApp/Installers/NodeRED